"""initial_master_schema"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

### end Alembic commands ###


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_admin_users_is_active'), 'admin_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_admin_users_role'), 'admin_users', ['role'], unique=False)
    op.create_table('admin_wizard_states',
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.String(length=150), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_id'), 'assignments', ['id'], unique=False)
    op.create_index(op.f('ix_assignments_request_id'), 'assignments', ['request_id'], unique=True)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_index(op.f('ix_assignments_tutor_id'), 'assignments', ['tutor_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='miniapp', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_telegram_id'), 'audit_log', ['actor_telegram_id'], unique=False)
    op.create_table('match_invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'tutor_id', name='uq_match_invites_request_tutor')
    )
    op.create_index(op.f('ix_match_invites_id'), 'match_invites', ['id'], unique=False)
    op.create_index(op.f('ix_match_invites_request_id'), 'match_invites', ['request_id'], unique=False)
    op.create_index(op.f('ix_match_invites_status'), 'match_invites', ['status'], unique=False)
    op.create_index(op.f('ix_match_invites_tutor_id'), 'match_invites', ['tutor_id'], unique=False)
    op.create_table('notification_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_id', sa.BigInteger(), nullable=True),
    sa.Column('topic_id', sa.BigInteger(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_outbox_event_key'), 'notification_outbox', ['event_key'], unique=False)
    op.create_index(op.f('ix_notification_outbox_status'), 'notification_outbox', ['status'], unique=False)
    op.create_table('parent_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('student_level', sa.String(length=100), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=False),
    sa.Column('preferred_gender', sa.String(length=50), nullable=False),
    sa.Column('preferred_experience', sa.String(length=100), nullable=False),
    sa.Column('location_subcity', sa.String(length=100), nullable=False),
    sa.Column('location_landmark', sa.String(length=255), nullable=True),
    sa.Column('schedule_days', sa.JSON(), nullable=False),
    sa.Column('time_slot', sa.String(length=100), nullable=False),
    sa.Column('session_duration', sa.String(length=50), nullable=False),
    sa.Column('budget_etb', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('telegram_topic_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_requests_id'), 'parent_requests', ['id'], unique=False)
    op.create_index(op.f('ix_parent_requests_location_subcity'), 'parent_requests', ['location_subcity'], unique=False)
    op.create_index(op.f('ix_parent_requests_preferred_gender'), 'parent_requests', ['preferred_gender'], unique=False)
    op.create_index(op.f('ix_parent_requests_status'), 'parent_requests', ['status'], unique=False)
    op.create_index(op.f('ix_parent_requests_telegram_user_id'), 'parent_requests', ['telegram_user_id'], unique=False)
    op.create_table('scheduled_event_claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('check_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_event_claims_check_type'), 'scheduled_event_claims', ['check_type'], unique=False)
    op.create_index(op.f('ix_scheduled_event_claims_event_key'), 'scheduled_event_claims', ['event_key'], unique=True)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tutors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('university', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('education_year', sa.String(length=100), nullable=False),
    sa.Column('subjects_qualified', sa.JSON(), nullable=False),
    sa.Column('grades_qualified', sa.JSON(), nullable=False),
    sa.Column('years_of_experience', sa.Float(), nullable=False),
    sa.Column('expected_fee_etb', sa.Float(), nullable=False),
    sa.Column('base_subcity', sa.String(length=100), nullable=False),
    sa.Column('coverage_areas', sa.JSON(), nullable=False),
    sa.Column('availability_schedule', sa.JSON(), nullable=False),
    sa.Column('id_document_url', sa.Text(), nullable=True),
    sa.Column('entrance_result_url', sa.Text(), nullable=True),
    sa.Column('entrance_result', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutors_base_subcity'), 'tutors', ['base_subcity'], unique=False)
    op.create_index(op.f('ix_tutors_gender'), 'tutors', ['gender'], unique=False)
    op.create_index(op.f('ix_tutors_id'), 'tutors', ['id'], unique=False)
    op.create_index(op.f('ix_tutors_is_paused'), 'tutors', ['is_paused'], unique=False)
    op.create_index(op.f('ix_tutors_status'), 'tutors', ['status'], unique=False)
    op.create_index(op.f('ix_tutors_telegram_user_id'), 'tutors', ['telegram_user_id'], unique=True)
    op.create_table('registration_funnel_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_funnel_events_session_id'), 'registration_funnel_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_registration_funnel_events_stage'), 'registration_funnel_events', ['stage'], unique=False)
    op.create_table('session_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_feedback_assignment_id'), 'session_feedback', ['assignment_id'], unique=False)
    op.create_table('tutor_incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reported_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_incidents_status'), 'tutor_incidents', ['status'], unique=False)
    op.create_index(op.f('ix_tutor_incidents_tutor_id'), 'tutor_incidents', ['tutor_id'], unique=False)
    op.create_table('tutor_verifications',
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('id_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('entrance_result_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('phone_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('claims_plausible', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('tutor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutor_verifications')
    op.drop_index(op.f('ix_tutor_incidents_tutor_id'), table_name='tutor_incidents')
    op.drop_index(op.f('ix_tutor_incidents_status'), table_name='tutor_incidents')
    op.drop_table('tutor_incidents')
    op.drop_index(op.f('ix_session_feedback_assignment_id'), table_name='session_feedback')
    op.drop_table('session_feedback')
    op.drop_index(op.f('ix_registration_funnel_events_stage'), table_name='registration_funnel_events')
    op.drop_index(op.f('ix_registration_funnel_events_session_id'), table_name='registration_funnel_events')
    op.drop_table('registration_funnel_events')
    op.drop_index(op.f('ix_tutors_telegram_user_id'), table_name='tutors')
    op.drop_index(op.f('ix_tutors_status'), table_name='tutors')
    op.drop_index(op.f('ix_tutors_is_paused'), table_name='tutors')
    op.drop_index(op.f('ix_tutors_id'), table_name='tutors')
    op.drop_index(op.f('ix_tutors_gender'), table_name='tutors')
    op.drop_index(op.f('ix_tutors_base_subcity'), table_name='tutors')
    op.drop_table('tutors')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_scheduled_event_claims_event_key'), table_name='scheduled_event_claims')
    op.drop_index(op.f('ix_scheduled_event_claims_check_type'), table_name='scheduled_event_claims')
    op.drop_table('scheduled_event_claims')
    op.drop_index(op.f('ix_parent_requests_telegram_user_id'), table_name='parent_requests')
    op.drop_index(op.f('ix_parent_requests_status'), table_name='parent_requests')
    op.drop_index(op.f('ix_parent_requests_preferred_gender'), table_name='parent_requests')
    op.drop_index(op.f('ix_parent_requests_location_subcity'), table_name='parent_requests')
    op.drop_index(op.f('ix_parent_requests_id'), table_name='parent_requests')
    op.drop_table('parent_requests')
    op.drop_index(op.f('ix_notification_outbox_status'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_event_key'), table_name='notification_outbox')
    op.drop_table('notification_outbox')
    op.drop_index(op.f('ix_match_invites_tutor_id'), table_name='match_invites')
    op.drop_index(op.f('ix_match_invites_status'), table_name='match_invites')
    op.drop_index(op.f('ix_match_invites_request_id'), table_name='match_invites')
    op.drop_index(op.f('ix_match_invites_id'), table_name='match_invites')
    op.drop_table('match_invites')
    op.drop_index(op.f('ix_audit_log_actor_telegram_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_assignments_tutor_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_request_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_table('admin_wizard_states')
    op.drop_index(op.f('ix_admin_users_role'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_is_active'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###